import torch
from resnet import ResNet  # include file, generated by build.py

# Create a neural network from auto-generated file
net = ResNet(in_channels=3, out_features=["res2", "res3", "res4", "res5"]).cuda()

# Create an image
data = torch.rand(1, 3, 256, 256, device="cuda")

# Execute network
print(net(data))