MODEL:
  BACKBONE:
    name: "resnet_fpn"  # Тип используемого backbone. {"resnet_fpn"}
    RESNETS:
      # Параметры для генерации ResNet
      depth: 50  # Глубина сети. {18, 34, 50, 101, 152}
      norm: "BN"  # Тип слоя нормализации. {"None", "BN", "FrozenBN"}
      num_groups: 1  # Количество групп для сверточных 3x3 слоев
      width_per_group: 64  # Количество каналов в каждой группе
      stem_out_channels: 64  # Количество каналов на выходе первого слоя
      res2_out_channels: 256  # Количество каналов на выходе второго слоя
      stride_in_1x1: True  # Будет ли stride проходить в слое 1x1 или же в слое 3x3
      res5_dilation: 1  # dilation в последнем слое. {1, 2}
      out_features: ["res2", "res3", "res4", "res5"]  # Какие слои будут выводиться.
    FPN:
      norm: "None"  # Тип слоя нормализации. {"None", "BN", "FrozenBN"}
      fuse_type: "sum"  # Способ объединения слоев. {"sum", "avg"}
      out_channels: 256  # Количество слоев на выходе
  PROPOSAL_GENERATOR:
    name: "RPN"  # Тип используемого PROPOSAL_GENERATOR. {"RPN"}
    RPN:
      head_name: "StandardRPNHead"
      batch_size_per_image: 256
      BBOX_REG:
        loss_type: "smooth_l1"
        loss_weight: 1.0
        weights: [1.0, 1.0, 1.0, 1.0]
      boundary_thresh: -1
      iou_labels: [0, -1, 1]
      iou_thresholds: [0.3, 0.7]
      loss_weight: 1.0
      nms_thress: 0.7
      POSITIVE_FRACTION: 0.5
      POST_NMS_TOPK_TEST: 1000
      POST_NMS_TOPK_TRAIN: 1000
      PRE_NMS_TOPK_TEST: 1000
      PRE_NMS_TOPK_TRAIN: 2000
      SMOOTH_L1_BETA: 0.0