MODEL:
  BACKBONE:
    name: "resnet_fpn"  # Тип используемого backbone. {"resnet_fpn"}
    RESNETS:
      # Параметры для генерации ResNet
      depth: 50  # Глубина сети. {18, 34, 50, 101, 152}
      norm: "BN"  # Тип слоя нормализации. {"None", "BN", "FrozenBN"}
      num_groups: 1  # Количество групп для сверточных 3x3 слоев
      width_per_group: 64  # Количество каналов в каждой группе
      stem_out_channels: 64  # Количество каналов на выходе первого слоя
      res2_out_channels: 256  # Количество каналов на выходе второго слоя
      stride_in_1x1: True  # Будет ли stride проходить в слое 1x1 или же в слое 3x3
      res5_dilation: 1  # dilation в последнем слое. {1, 2}
      out_features: ["res2", "res3", "res4", "res5"]  # Какие слои будут выводиться.
    FPN:
      norm: "None"  # Тип слоя нормализации. {"None", "BN", "FrozenBN"}
      fuse_type: "sum"  # Способ объединения слоев. {"sum", "avg"}
      out_channels: 256  # Количество слоев на выходе
  PROPOSAL_GENERATOR:
    name: "RPN"  # Тип используемого PROPOSAL_GENERATOR. {"RPN"}
    RPN:
      head_name: "StandardRPNHead"
      ANCHOR_GENERATOR:
        aspect_ratios: [0.5, 1.0, 2.0]
        sizes: [32, 64, 128, 256, 512]
      IOU:
        labels: [0, -1, 1]
        thresholds: [0.3, 0.7]
      LOSS:
        type: "smooth_l1"
        cls_weight: 1.0
        loc_weight: 1.0
      TRAIN:
        batch_size_per_image: 256
        post_topk: 1000
        pre_topk: 2000
        positive_fraction: 0.5
      TEST:
        post_topk: 1000
        pre_topk: 1000
      nms_thress: 0.7
      smooth_l1_beta: 0.0